JobDiscover/core/urls.py
from django.urls import path

from JobDiscover.core.views import IndexView, CompanyProfileView, ApplicantProfileView, CompanyEditView, \
    ApplicantEditView, CompanyListView, delete_user

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('profile-company/<int:pk>', CompanyProfileView.as_view(), name='company profile'),
    path('profile-company/edit/<int:pk>', CompanyEditView.as_view(), name='company edit'),
    path('profile-applicant/<int:pk>', ApplicantProfileView.as_view(), name='applicant profile'),
    path('profile-applicant/edit/<int:pk>', ApplicantEditView.as_view(), name='applicant edit'),
    path('delete/<int:pk>', delete_user, name='user delete'),
    path('companies/', CompanyListView.as_view(), name='company list'),
]

JobDiscover/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('JobDiscover.core.urls')),
    path('auth/', include('JobDiscover.jobs_auth.urls')),
    path('jobs/', include('JobDiscover.jobs.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

JobDiscover/core/models.py
from django.db import models

JobDiscover/jobs/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models
from django_resized import ResizedImageField
from multiselectfield import MultiSelectField

from JobDiscover.core.validators import validate_is_doc, validate_start_with_capital
from JobDiscover.jobs_auth.models import ApplicantProfile, CompanyProfile

UserModel = get_user_model()


class Job(models.Model):
    AUTOMOTIVE = 'automotive'
    ACCOUNTING = 'accounting'
    BANKING = 'banking'
    CALL_CENTER = 'call_center'
    CLEANING = 'cleaning'
    DRIVING = 'driving'
    DESIGN = 'design'
    EDUCATION = 'education'
    HEALTHCARE = 'healthcare'
    IT = 'it'
    LEGAL = 'legal'
    MANAGEMENT = 'management'
    MEDIA = 'media'
    RESTAURANTS = 'restaurants'
    SECURITY = 'security'

    CATEGORY_CHOICES = [
        (AUTOMOTIVE, 'Automotive, Auto Service'),
        (ACCOUNTING, 'Accounting, Finance'),
        (BANKING, 'Banking, Lending'),
        (CALL_CENTER, 'Call Center, Customer Support'),
        (CLEANING, 'Cleaning, Household Services'),
        (DRIVING, 'Drivers, Couriers'),
        (DESIGN, 'Design'),
        (EDUCATION, 'Education'),
        (HEALTHCARE, 'Healthcare, Pharmacy'),
        (IT, 'Information Technology, Development'),
        (LEGAL, 'Legal'),
        (MANAGEMENT, 'Management'),
        (MEDIA, 'Media, Publishing'),
        (RESTAURANTS, 'Restaurants, Hotels, Bars'),
        (SECURITY, 'Security'),
    ]

    FULL_TIME = 'full_time'
    FOR_STUDENTS = 'for_students'
    FREELANCE = 'freelance'
    INTERNSHIP = 'internship'
    LITTLE_EXPERIENCE = 'little_experience'
    PART_TIME = 'part_time'

    TYPE_CHOICES = [
        (FULL_TIME, 'Full Time'),
        (FOR_STUDENTS, 'For Students'),
        (FREELANCE, 'Freelance'),
        (INTERNSHIP, 'Internship'),
        (LITTLE_EXPERIENCE, 'Candidates with little or no experience'),
        (PART_TIME, 'Part Time'),
    ]

    title = models.CharField(max_length=75)
    description = models.TextField(max_length=5000)
    date_created = models.DateField(auto_now_add=True)
    category = models.CharField(max_length=15, choices=CATEGORY_CHOICES)
    location = models.CharField(max_length=25, validators=(validate_start_with_capital,))
    type = MultiSelectField(choices=TYPE_CHOICES)
    salary = models.IntegerField(blank=True, null=True, validators=[MinValueValidator(1)])
    image = ResizedImageField(
        size=[800, 200],
        crop=['middle', 'center'],
        quality=100,
        upload_to='jobs',
        blank=True,
        null=True,
        help_text="Use image with 800x200px for best results.",
    )

    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Application(models.Model):
    motivational_letter = models.TextField(max_length=2000)
    cv = models.FileField(upload_to='applications', validators=(validate_is_doc,))
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    applicant = models.ForeignKey(ApplicantProfile, on_delete=models.CASCADE)
    company = models.ForeignKey(CompanyProfile, on_delete=models.CASCADE)

JobDiscover/core/forms.py
from django import forms

from JobDiscover.core.validators import validate_image_file_size
from JobDiscover.jobs_auth.models import CompanyProfile, ApplicantProfile


class BootstrapFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_fields()

    def _init_bootstrap_fields(self):
        fields = self.fields.items()
        for (name, field) in fields:
            if name != 'type':
                if 'class' not in field.widget.attrs:
                    field.widget.attrs['class'] = ''
                field.widget.attrs['class'] += ' form-control'


class EditCompanyForm(BootstrapFormMixin, forms.ModelForm):
    class Meta:
        model = CompanyProfile
        exclude = ('user', 'name')

    def clean_company_icon(self):
        icon = self.cleaned_data.get('company_icon')
        validate_image_file_size(icon)
        return icon

    def clean_company_banner(self):
        banner = self.cleaned_data.get('company_banner')
        validate_image_file_size(banner)
        return banner


class EditApplicantForm(BootstrapFormMixin, forms.ModelForm):
    class Meta:
        model = ApplicantProfile
        exclude = ('user',)

    def clean_profile_image(self):
        image = self.cleaned_data.get('profile_image')
        validate_image_file_size(image)
        return image

JobDiscover/core/views.py
from django.http import HttpResponseForbidden, Http404
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import DetailView, UpdateView, ListView

from JobDiscover.core.forms import EditCompanyForm, EditApplicantForm
from JobDiscover.jobs.models import Job, Application
from JobDiscover.jobs_auth.models import CompanyProfile, ApplicantProfile, JobDiscoverUser


class IndexView(ListView):
    template_name = 'core/index.html'
    model = Job
    paginate_by = 5

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset()
        query = self.request.GET.get('q')
        if query:
            return qs.filter(title__icontains=query)
        return qs

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context.update({
            'company_list': CompanyProfile.objects.order_by('name'),
        })
        query = self.request.GET.copy()
        if 'page' in query:
            del query['page']
        context['queries'] = query
        context['job_count'] = Job.objects.all().count()
        return context


class CompanyProfileView(DetailView):
    template_name = 'core/company-profile.html'
    model = CompanyProfile

    def get_context_data(self, **kwargs):
        context = super(CompanyProfileView, self).get_context_data(**kwargs)
        context['is_profile_owner'] = self.object.pk == self.request.user.id
        context['jobs_list'] = self.get_job_list()
        context['application_list'] = self.get_application_list()
        return context

    def get_job_list(self):
        job_list = Job.objects.filter(user_id=self.object.pk)
        return job_list

    def get_application_list(self):
        application_list = Application.objects.filter(company_id=self.object.pk)
        return application_list


class CompanyEditView(UpdateView):
    template_name = 'core/company-edit.html'
    form_class = EditCompanyForm
    model = CompanyProfile

    def get_success_url(self):
        return reverse('company profile', kwargs={'pk': self.object.pk})

    def get(self, request, *args, **kwargs):
        if not request.user.id == self.kwargs.get('pk'):
            return HttpResponseForbidden()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if not request.user.id == self.kwargs.get('pk'):
            return HttpResponseForbidden()
        return super().post(request, *args, **kwargs)


def delete_user(request, pk):
    user = JobDiscoverUser.objects.get(pk=pk)
    if request.method == 'POST' and request.user.id == user.id:
        user.delete()
        return redirect('index')
    else:
        raise Http404('Page not found')


class ApplicantProfileView(DetailView):
    template_name = 'core/applicant-profile.html'
    model = ApplicantProfile

    def get_context_data(self, **kwargs):
        context = super(ApplicantProfileView, self).get_context_data(**kwargs)
        context['is_profile_owner'] = self.object.pk == self.request.user.id
        return context

    def get(self, request, *args, **kwargs):
        if not request.user.id == self.kwargs.get('pk'):
            return HttpResponseForbidden()
        return super().get(request, *args, **kwargs)


class ApplicantEditView(UpdateView):
    template_name = 'core/applicant-edit.html'
    form_class = EditApplicantForm
    model = ApplicantProfile

    def get_success_url(self):
        return reverse('applicant profile', kwargs={'pk': self.object.pk})

    def get(self, request, *args, **kwargs):
        if not request.user.id == self.kwargs.get('pk'):
            return HttpResponseForbidden()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if not request.user.id == self.kwargs.get('pk'):
            return HttpResponseForbidden()
        return super().post(request, *args, **kwargs)


class CompanyListView(ListView):
    template_name = 'core/company-list.html'
    model = CompanyProfile
    context_object_name = 'companies'
    paginate_by = 9

templates/core/applicant-edit.html
{% extends 'shared/base.html' %}

{% block content %}
    <form method="post" action="{% url 'applicant edit' object.pk %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <br><br>
        <button type="submit" class="btn btn-md btn-outline-info">Save changes</button>
        <p></p>
    </form>
{% endblock %}

templates/core/applicant-profile.html
{% extends 'shared/base.html' %}
{% load static %}

{% block content %}
    <div class="container" style="padding-top: 3%; padding-bottom: 1%">
        <div class="main-body">
            <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                    <div class="card" style="border-color: midnightblue">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                {% if object.profile_image %}
                                    <img src="{{ object.profile_image.url }}" alt="" class="rounded-circle" width="150">
                                {% else %}
                                    <img src="{% static 'images/applicantDefaultImage.png' %}" alt=""
                                         class="rounded-circle" width="150">
                                {% endif %}

                                <div class="mt-3">
                                    <h4>{{ object.first_name }} {{ object.last_name }}</h4>
                                    {% if object.bio %}
                                        <hr>
                                        <h5>Bio</h5>
                                        <p class="text-secondary mb-1 d-inline">{{ object.bio }}</p>
                                    {% elif is_profile_owner %}
                                        <p>Add your bio with the edit button</p>
                                    {% endif %}
                                    {% if is_profile_owner %}
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <hr>
                                                <a class="btn btn-md btn-outline-secondary"
                                                   href="{% url 'applicant edit' object.user_id %}">Edit profile
                                                </a>
                                                <form style="display: inline" action="{% url 'user delete' object.pk %}" method="post">
                                                    {% csrf_token %}
                                                    <button type="submit" class="btn btn-md btn-outline-danger"
                                                        onclick="return confirm('Are you sure you want to delete your profile? You cannot restore it afterwards!');">Delete profile
                                                    </button>
                                                </form>
                                            </div>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="col-md-8">
                    <div class="card mb-3" style="border-color: midnightblue">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Email</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{ object.user.email }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">First name</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{ object.first_name }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Last name</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{ object.last_name }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/core/company-edit.html
{% extends 'shared/base.html' %}

{% block content %}
    <br>
    <form method="post" action="{% url 'company edit' object.pk %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br><br>
        <button type="submit" class="btn btn-md btn-outline-info">Save changes</button>
        <p></p>
    </form>
{% endblock %}

templates/core/company-list.html
{% extends 'shared/base.html' %}
{% load static %}

{% block content %}
    <br>
    <h1 class="text-center">All Companies</h1>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="row" style="padding-top: 3%; padding-bottom: 2%">
                    {% for company in companies %}
                        <div class="col-sm-6 col-lg-4 mb-4">
                            <a style="color: #495057; text-decoration-color: midnightblue"
                               href="{% url 'company profile' company.user_id %}">
                                <div class="card" style="border-color: midnightblue; padding-top: 5%">
                                    {% if company.company_icon %}
                                        <div class="text-center">
                                            <img src="{{ company.company_icon.url }}" alt="">
                                        </div>
                                    {% else %}
                                        <div class="text-center">
                                            <img src="{% static 'images/companyDefaultLogo.png' %}" alt="">
                                        </div>
                                    {% endif %}
                                    <div style="text-align: center">
                                        <h3>{{ company.name }}</h3>
                                        <p>
                                            <span class="badge badge-primary badge-pill"
                                                  style="">Adverts: {{ company.user.job_set.count }}</span>
                                        </p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <nav>
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo; First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                </li>
            {% endif %}
            <li class="page-item disabled">
                <a class="page-link disabled">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
            </li>
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

templates/core/index.html
{% extends 'shared/base.html' %}
{% load static %}

{% block content %}

    <div style="text-align: center; padding-top: 5%">
        <h1> {{ job_count }} Job adverts </h1>
        <h3 style="color: midnightblue"> The next gen job finder</h3>
    </div>

    <div class="row d-flex justify-content-center mt-100 mb-100">
        <div class="col-lg-10" style="padding-bottom: 5%; padding-top: 5%">
            <form class="form-inline my-2 my-lg-0 input-group" method="GET" action="">
                <input class="form-control rounded mr-sm-2" type="search" name="q" placeholder="Search by job title"
                       aria-describedby="search-addon"
                       value="{{ request.GET.q }}">
                <input type="submit" value="Search" class="btn btn-outline-secondary">
            </form>
        </div>
    </div>
    <div class="row d-flex justify-content-center mt-100 mb-100">
        <div class="col-lg-10">
            <div class="list-group list-group-flush">
                {% if object_list %}
                    {% for obj in object_list %}
                        <a href="{% url 'job detail' obj.id %}" class="list-group-item list-group-item-action"#}
                           style="border-color: midnightblue">
                            <small>{{ obj.date_created|date:"d/m/y" }}</small>
                            <div class="d-flex w-100 justify-content-between">
                                <h4 class="mb-1">{{ obj.title }}</h4>
                                <h5>{{ obj.user.companyprofile.name }}</h5>
                            </div>
                            <h6 style="display: inline">{{ obj.location }}</h6>
                            {% if obj.salary %}
                                <h6 style="display: inline">| Salary - {{ obj.salary }} BGN</h6>
                            {% endif %}
                        </a>
                    {% endfor %}
                {% else %}
                    <p>No results match your search</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row d-flex justify-content-center mt-100 mb-100">
        <div class="col-lg-10">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% if is_paginated %}
                        {% if page_obj.has_previous %}
                            <li style="display: inline">
                                <a href="?{{ queries.urlencode }}&amp;page=1"><i
                                        class="page-link fa fa-angle-double-left"></i></a>
                            </li>
                            <li style="display: inline">
                                <a href="?{{ queries.urlencode }}&amp;page={{ page_obj.previous_page_number }}"><i
                                        class="page-link fa fa-angle-left"></i></a>
                            </li>
                        {% else %}
                            <li style="display: inline" class="page-item disabled">
                                <a href="#" class="page-link fa fa-angle-double-left"></a>
                            </li>
                            <li style="display: inline" class="page-item disabled">
                                <a href="#" class="page-link fa fa-angle-left"></a>
                            </li>
                        {% endif %}

                        {% for i in page_obj.paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="page-link" style="display: inline; background-color: midnightblue">
                                    <a href="#" style="color: white">{{ i }}</a>
                                </li>
                            {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
                                <li style="display: inline">
                                    <a class="page-link" href="?{{ queries.urlencode }}&amp;page={{ i }}">{{ i }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li style="display: inline">
                                <a href="?{{ queries.urlencode }}&amp;page={{ page_obj.next_page_number }}"><i
                                        class="page-link fa fa-angle-right"></i></a>
                            </li>
                            <li style="display: inline">
                                <a href="?{{ queries.urlencode }}&amp;page={{ page_obj.paginator.num_pages }}"><i
                                        class="page-link fa fa-angle-double-right"></i></a>
                            </li>
                        {% else %}
                            <li style="display: inline" class="page-item disabled">
                                <a href="#" class="page-link fa fa-angle-right"></a>
                            </li>
                            <li style="display: inline" class="page-item disabled">
                                <a href="#" class="page-link fa fa-angle-double-right"></a>
                            </li>
                        {% endif %}
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
    <br>
    <h1 style="text-align: center">Companies</h1>
    <div class="row d-flex justify-content-center mt-100 mb-100">
        <div class="col-lg-10">
            <div class="row" style="padding-top: 3%; padding-bottom: 2%">
                {% for company in company_list %}
                    <div class="col-sm-6 col-lg-4 mb-4">
                        <a style="color: #495057; text-decoration-color: midnightblue"
                           href="{% url 'company profile' company.user_id %}">
                            <div class="card" style="border-color: midnightblue; padding-top: 5%">
                                {% if company.company_icon %}
                                    <div class="text-center">
                                        <img src="{{ company.company_icon.url }}" alt="">
                                    </div>
                                {% else %}
                                    <div class="text-center">
                                        <img src="{% static 'images/companyDefaultLogo.png' %}" alt="">
                                    </div>
                                {% endif %}

                                <div style="text-align: center">
                                    <h3>{{ company.name }}</h3>
                                    <p>
                                        <span class="badge badge-primary badge-pill"
                                              style="">Adverts: {{ company.user.job_set.count }}
                                        </span>
                                    </p>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}